### ISSUE TITLE
RTM Deprecation

### ISSUE THREAD

**Issue by djbe** [SlackKit/SlackKit#203]
I noticed this when I tried to get started writing a new slack app with this framework, but the sample code didn't work at all. Only when I used network debugging did I notice that the initial call to `https://api.slack.com/rtm` fails with a "deprecated" error.

-----

According to the Slack documentation:
> New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.

With an additional notice of:
> rtm.start is deprecated and behavior for existing users will change on September 30, 2022.

The Slack docs recommend using [Socket Mode](https://api.slack.com/apis/connections/socket), or using the [Events API](https://api.slack.com/apis/connections/events-api).

-----

From a quick search through this repository, socket mode doesn't seem supported yet. I don't think the events api is implemented yet either? Not certain though, it seems one is more a transport layer, and the other is more an application layer 🤷

**Comment by pvzig** [comment]
Yeah, looks like RTM was still defaulting to using the old `rtm.start` API call and not `rtm.connect`. Updated and [removed](https://github.com/pvzig/SlackKit/commit/ab751a03048279eda00aa19325d28518431ec820).

**Comment by djbe** [comment]
Hi @pvzig,

I apologize, I should probably have created a separate issue for the rtm "deprecated issue". The main issue could be subdivided in a few items:
- rtm.start was obsolete, which you've solved with ab751a03048279eda00aa19325d28518431ec820
- New slack apps must use oauth scopes
- As a consequence of using scopes, new slack apps no longer support RTM
- The OAuth flow implementation is broken at multiple points (I think) for "classic" apps, see #206.
