### ISSUE TITLE
OAuth (client ID/secret) doesn't work

### ISSUE THREAD

**Issue by djbe** [SlackKit/SlackKit#206]
OAuth doesn't work because a few reasons:
1. The respone code cannot be extracted from the path (https://github.com/pvzig/SlackKit/blob/main/SKServer/Sources/Conformers/SwifterServer.swift#L60), because the path no longer contains query items. To get those, the property `queryParams` (a `[(String, String)]` must be used.
2. Further it keeps failing with `oauth_authorization_url_mismatch`, even though the request to slack.com/api/oauth.v2.access contains the same redirect url as configured in the app on slack

The first issue I was able to solve by adding a `queryParams` to the protocol & struct, and use that instead of extracting query parameters from the `path`. I'm still stuck with item 2. There may be more issues after that 🤷 It might be related to #203.

Note: I'm trying this with a "legacy" slack app, as otherwise it wouldn't support RTM (see #203)

**Comment by djbe** [comment]
Here's an example of how to fix queryParams extraction from a request:
https://github.com/djbe/SlackKit/commit/e34a1df3aba0a5f03eca0242682da9c9cd4b2396

**Comment by djbe** [comment]
I was able to solve the 2nd issue by reverting the `oauthAccess` path (https://github.com/pvzig/SlackKit/blob/main/SKWebAPI/Sources/Endpoint.swift#L73) from `oauth.v2.access` to the old `oauth.access` path. After that it correctly gets access & bot tokens, and RTM connects.

Branch with both queryParams & path fixes:
https://github.com/djbe/SlackKit/tree/fix/query-params

**Comment by pvzig** [comment]
[Merged](https://github.com/pvzig/SlackKit/pull/207) and released in https://github.com/pvzig/SlackKit/releases/tag/4.8.0. Thanks!
