### ISSUE TITLE
incomplete definition of type 'struct bio_st'

### ISSUE THREAD

**Issue by sherryshao** [SlackKit/SlackKit#211]
Wanted to take advantage of this framework and set it up in my SPM - I did install (homebrew) libressl as suggested, but am still getting some errors upon adding `SlackKit` as a dependency in my project targets:

<img width="348" alt="Screen Shot 2022-06-02 at 4 56 48 PM" src="https://user-images.githubusercontent.com/1714382/171759191-8d584bcb-69c5-42b1-8545-ecccc08f155d.png">

I also attempted a suggestion to just remove exclude the vapor websocket framework - but that didn't seem to work either.

Any guidance would be greatly appreciated!

**Comment by cyrillelegrand** [comment]
Same here.
Xcode 13.4.1
macOS 12.4
SlackKit 4.8.0
Libressl stable 3.5.3 installed with Homebrew 3.4.11

Same error from within Xcode or from `swift build`.

**Comment by elbuki** [comment]
I'm experiencing the same issue. Is this error specific to M1? Please help!

**Comment by shimastripe** [comment]
@elbuki https://github.com/pvzig/SlackKit/pull/212 I submitted updating SwiftNIO version PR.  Is this resolved in master?
